version: '3.8'
services:
  mongo:
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
  auth-service:
    image: quay.io/prateekjain/auth-service:latest
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/auth-service
    depends_on:
      - mongo
  user-service:
    image: quay.io/prateekjain/user-service:latest
    ports:
      - "3002:3002"
    environment:
      - MONGO_URL=mongodb://mongo:27017/user-service
    depends_on:
      - mongo
  product-service:
    image: quay.io/prateekjain/product-service:latest
    ports:
      - "3003:3003"
    environment:
      - MONGO_URL=mongodb://mongo:27017/product-service
    depends_on:
      - mongo
  order-service:
    image: quay.io/prateekjain/order-service:latest
    ports:
      - "3004:3004"
    environment:
      - MONGO_URL=mongodb://mongo:27017/order-service
      - PRODUCT_SERVICE_URL=http://product-service:3003
    depends_on:
      - mongo
      - product-service
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - auth-service
      - user-service
      - product-service
      - order-service
