name: Inventory Service CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'inventory-service/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'inventory-service/**'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      service_name: 'inventory-service'
      service_path: './inventory-service'
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
